#!/usr/bin/env python3
"""Codegen app/components/itemIconMapDark.ts from itemIconMap.ts.

The dark map mirrors the four light require-maps exactly (same keys, same alias
styles) with the asset directory swapped to its `-dark` sibling. React Native's
Metro bundler needs literal require() paths, so the maps cannot be derived at
runtime — this script keeps the dark map in sync with the light one mechanically.

Run after editing the light maps in itemIconMap.ts or adding/removing icons:
  python3 scripts/dark-icons/generate-dark-map.py
"""
import io
import os
import re

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
SRC = os.path.join(REPO, "app", "components", "itemIconMap.ts")
OUT = os.path.join(REPO, "app", "components", "itemIconMapDark.ts")

# (source const name, exported dark const name)
# Letter fallbacks are rendered as CasinoGrotesk text glyphs (themed at runtime),
# not images, so only the item maps need dark variants.
MAPS = [
    ("ITEM_ICONS", "ITEM_ICONS_DARK"),
    ("MINIMAL_ITEM_ICONS", "MINIMAL_ITEM_ICONS_DARK"),
]

DIR_SWAP = [
    ("items/illustrated/", "items/illustrated-dark/"),
    ("items/minimal/", "items/minimal-dark/"),
]


def extract_block(src, name):
    m = re.search(r"\bconst\s+" + re.escape(name) + r"\b", src)
    if not m:
        raise SystemExit(f"map not found: {name}")
    brace = src.index("{", m.end())
    depth = 0
    for i in range(brace, len(src)):
        c = src[i]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return src[m.start():i + 1]
    raise SystemExit(f"unbalanced braces for {name}")


def main():
    src = open(SRC, encoding="utf-8").read()
    out = io.StringIO()
    out.write("// AUTO-GENERATED by scripts/dark-icons/generate-dark-map.py (do not edit by hand).\n")
    out.write("// Dark-mode require maps mirroring itemIconMap.ts, pointing at the *-dark asset dirs.\n")
    out.write("// Regenerate after changing the light maps or icon assets.\n\n")
    out.write("import type { ImageSourcePropType } from 'react-native'\n\n")

    for name, dark_name in MAPS:
        block = extract_block(src, name)
        block = block.replace(f"const {name}", f"export const {dark_name}", 1)
        for a, b in DIR_SWAP:
            block = block.replace(a, b)
        out.write(block)
        out.write("\n\n")

    open(OUT, "w", encoding="utf-8").write(out.getvalue())
    print("wrote", os.path.relpath(OUT, REPO))


if __name__ == "__main__":
    main()
