export const CATEGORY_ORDER: string[] = [
    'Fruits',
    'Vegetables',
    'Bread & Bakery',
    'Deli',
    'Meat',
    'Fish & Seafood',
    'Dairy',
    'Canned Goods',
    'Pasta/Rice/Cereal',
    'Condiments & Spices',
    'Baking',
    'Snacks',
    'Beverages',
    'Frozen Foods',
    'Ready Meals',
    'International Foods',
    'Health & Organic',
    'Personal Care',
    'Household & Cleaning',
    'Baby Items',
    'Pet Care',
    'Others',
]

export const CATEGORY_ICONS: Record<string, string> = {
    'Fruits': 'nutrition-outline',
    'Vegetables': 'leaf-outline',
    'Bread & Bakery': 'bread-outline',
    'Deli': 'restaurant-outline',
    'Meat': 'flame-outline',
    'Fish & Seafood': 'fish-outline',
    'Dairy': 'water-outline',
    'Canned Goods': 'cube-outline',
    'Pasta/Rice/Cereal': 'pizza-outline',
    'Condiments & Spices': 'flask-outline',
    'Baking': 'cafe-outline',
    'Snacks': 'fast-food-outline',
    'Beverages': 'beer-outline',
    'Frozen Foods': 'snow-outline',
    'Ready Meals': 'time-outline',
    'International Foods': 'globe-outline',
    'Health & Organic': 'heart-outline',
    'Personal Care': 'body-outline',
    'Household & Cleaning': 'home-outline',
    'Baby Items': 'happy-outline',
    'Pet Care': 'paw-outline',
    'Others': 'basket-outline',
}
