import type { ImageSourcePropType } from 'react-native'
import { TRANSLATED_ITEM_TO_EN } from './itemTranslations'

// Static require maps — React Native needs literal require() calls

const ITEM_ICONS: Record<string, ImageSourcePropType> = {
    // ── Fruits ──────────────────────────────────────────────────────────────
    apple: require('../assets/icons/items/apple.png'),
    apples: require('../assets/icons/items/apple.png'),
    'apple juice': require('../assets/icons/items/apple-juice-carton.png'),
    banana: require('../assets/icons/items/bananas.png'),
    bananas: require('../assets/icons/items/bananas.png'),
    grape: require('../assets/icons/items/grapes.png'),
    grapes: require('../assets/icons/items/grapes.png'),
    strawberry: require('../assets/icons/items/strawberries.png'),
    strawberries: require('../assets/icons/items/strawberries.png'),
    blueberry: require('../assets/icons/items/blueberries.png'),
    blueberries: require('../assets/icons/items/blueberries.png'),
    blackberry: require('../assets/icons/items/blackberries.png'),
    blackberries: require('../assets/icons/items/blackberries.png'),
    cherry: require('../assets/icons/items/cherries.png'),
    cherries: require('../assets/icons/items/cherries.png'),
    avocado: require('../assets/icons/items/avocado.png'),
    avocados: require('../assets/icons/items/avocado.png'),
    lemon: require('../assets/icons/items/lemons.png'),
    lemons: require('../assets/icons/items/lemons.png'),
    orange: require('../assets/icons/items/oranges.png'),
    oranges: require('../assets/icons/items/oranges.png'),
    grapefruit: require('../assets/icons/items/grapefruit.png'),
    kiwi: require('../assets/icons/items/kiwi.png'),
    kiwis: require('../assets/icons/items/kiwi.png'),
    melon: require('../assets/icons/items/melon.png'),
    watermelon: require('../assets/icons/items/watermelon.png'),
    pineapple: require('../assets/icons/items/pineapple.png'),
    mango: require('../assets/icons/items/apple.png'), // no mango icon, fallback
    peach: require('../assets/icons/items/peach.png'),
    peaches: require('../assets/icons/items/peach.png'),
    pear: require('../assets/icons/items/pear.png'),
    pears: require('../assets/icons/items/pear.png'),
    plum: require('../assets/icons/items/plum.png'),
    plums: require('../assets/icons/items/plum.png'),
    nectarine: require('../assets/icons/items/nectarine.png'),
    nectarines: require('../assets/icons/items/nectarine.png'),
    clementine: require('../assets/icons/items/clementine.png'),
    clementines: require('../assets/icons/items/clementine.png'),
    tangerine: require('../assets/icons/items/clementine.png'),
    tangerines: require('../assets/icons/items/clementine.png'),
    coconut: require('../assets/icons/items/coconut.png'),
    fig: require('../assets/icons/items/figs.png'),
    figs: require('../assets/icons/items/figs.png'),
    dates: require('../assets/icons/items/dates.png'),
    date: require('../assets/icons/items/dates.png'),
    'passion fruit': require('../assets/icons/items/passion-fruit.png'),
    papaya: require('../assets/icons/items/papaya.png'),
    pomegranate: require('../assets/icons/items/pomegranate.png'),

    // ── Vegetables ──────────────────────────────────────────────────────────
    tomato: require('../assets/icons/items/tomato.png'),
    tomatoes: require('../assets/icons/items/tomato.png'),
    potato: require('../assets/icons/items/potatoes.png'),
    potatoes: require('../assets/icons/items/potatoes.png'),
    'sweet potato': require('../assets/icons/items/sweet-potatoes.png'),
    'sweet potatoes': require('../assets/icons/items/sweet-potatoes.png'),
    onion: require('../assets/icons/items/onion.png'),
    onions: require('../assets/icons/items/onion.png'),
    'spring onion': require('../assets/icons/items/spring-onions.png'),
    'spring onions': require('../assets/icons/items/spring-onions.png'),
    scallion: require('../assets/icons/items/spring-onions.png'),
    scallions: require('../assets/icons/items/spring-onions.png'),
    garlic: require('../assets/icons/items/garlic-fresh.png'),
    carrot: require('../assets/icons/items/carrots.png'),
    carrots: require('../assets/icons/items/carrots.png'),
    broccoli: require('../assets/icons/items/broccoli.png'),
    spinach: require('../assets/icons/items/spinach-leaves.png'),
    'spinach leaves': require('../assets/icons/items/spinach-leaves.png'),
    salad: require('../assets/icons/items/salad-lettuce-iceberg.png'),
    lettuce: require('../assets/icons/items/salad-lettuce-iceberg.png'),
    iceberg: require('../assets/icons/items/salad-lettuce-iceberg.png'),
    cucumber: require('../assets/icons/items/cucumbers.png'),
    cucumbers: require('../assets/icons/items/cucumbers.png'),
    'bell pepper': require('../assets/icons/items/bell-peppers.png'),
    'bell peppers': require('../assets/icons/items/bell-peppers.png'),
    pepper: require('../assets/icons/items/pepper.png'),
    peppers: require('../assets/icons/items/pepper.png'),
    'black pepper': require('../assets/icons/items/pepper-shaker.png'),
    zucchini: require('../assets/icons/items/zucchini.png'),
    courgette: require('../assets/icons/items/zucchini.png'),
    eggplant: require('../assets/icons/items/eggplant.png'),
    aubergine: require('../assets/icons/items/eggplant.png'),
    mushroom: require('../assets/icons/items/mushrooms.png'),
    mushrooms: require('../assets/icons/items/mushrooms.png'),
    corn: require('../assets/icons/items/corn.png'),
    'sweet corn': require('../assets/icons/items/corn.png'),
    'green beans': require('../assets/icons/items/green-beans.png'),
    'green bean': require('../assets/icons/items/green-beans.png'),
    beans: require('../assets/icons/items/beans.png'),
    bean: require('../assets/icons/items/beans.png'),
    cabbage: require('../assets/icons/items/cabbage.png'),
    cauliflower: require('../assets/icons/items/cauliflower.png'),
    asparagus: require('../assets/icons/items/asparagus-spears.png'),
    leek: require('../assets/icons/items/leek.png'),
    leeks: require('../assets/icons/items/leek.png'),
    radish: require('../assets/icons/items/radishes.png'),
    radishes: require('../assets/icons/items/radishes.png'),
    beetroot: require('../assets/icons/items/beetroot.png'),
    beet: require('../assets/icons/items/beetroot.png'),
    artichoke: require('../assets/icons/items/artichoke.png'),
    artichokes: require('../assets/icons/items/artichoke.png'),
    parsnip: require('../assets/icons/items/parsnip.png'),
    parsnips: require('../assets/icons/items/parsnip.png'),
    turnip: require('../assets/icons/items/turnip.png'),
    turnips: require('../assets/icons/items/turnip.png'),
    arugula: require('../assets/icons/items/arugula-rocket-leaves.png'),
    rocket: require('../assets/icons/items/arugula-rocket-leaves.png'),
    radicchio: require('../assets/icons/items/radicchio.png'),
    butternut: require('../assets/icons/items/butternut.png'),
    'butternut squash': require('../assets/icons/items/butternut.png'),
    ginger: require('../assets/icons/items/ginger-root.png'),
    // herbs
    basil: require('../assets/icons/items/fresh-basil-herb.png'),
    'fresh basil': require('../assets/icons/items/fresh-basil-herb.png'),
    parsley: require('../assets/icons/items/fresh-parsley-herb.png'),
    'fresh parsley': require('../assets/icons/items/fresh-parsley-herb.png'),
    cilantro: require('../assets/icons/items/cilantro-coriander.png'),
    coriander: require('../assets/icons/items/cilantro-coriander.png'),
    dill: require('../assets/icons/items/dill-herb.png'),
    rosemary: require('../assets/icons/items/rosemary-sprigs.png'),
    oregano: require('../assets/icons/items/oregano-dried-herbs.png'),
    herbs: require('../assets/icons/items/oregano-dried-herbs.png'),
    'dried herbs': require('../assets/icons/items/oregano-dried-herbs.png'),

    // ── Bread & Bakery ───────────────────────────────────────────────────────
    bread: require('../assets/icons/items/baguette-bread.png'),
    baguette: require('../assets/icons/items/baguette-bread.png'),
    toast: require('../assets/icons/items/toast-bread.png'),
    croissant: require('../assets/icons/items/croissants-pastry-sweets.png'),
    croissants: require('../assets/icons/items/croissants-pastry-sweets.png'),
    pastry: require('../assets/icons/items/croissants-pastry-sweets.png'),
    sweets: require('../assets/icons/items/croissants-pastry-sweets.png'),
    bagel: require('../assets/icons/items/bagels-donuts.png'),
    bagels: require('../assets/icons/items/bagels-donuts.png'),
    donut: require('../assets/icons/items/bagels-donuts.png'),
    donuts: require('../assets/icons/items/bagels-donuts.png'),
    cake: require('../assets/icons/items/cake.png'),
    biscuit: require('../assets/icons/items/biscuits.png'),
    biscuits: require('../assets/icons/items/biscuits.png'),
    wraps: require('../assets/icons/items/wraps.png'),
    wrap: require('../assets/icons/items/wraps.png'),
    tortilla: require('../assets/icons/items/wraps.png'),
    tortillas: require('../assets/icons/items/wraps.png'),

    // ── Deli ────────────────────────────────────────────────────────────────
    salami: require('../assets/icons/items/salami.png'),
    hummus: require('../assets/icons/items/hummus.png'),
    mortadella: require('../assets/icons/items/sliced-mortadella.png'),
    'turkey breast': require('../assets/icons/items/sliced-turkey-breast.png'),
    chorizo: require('../assets/icons/items/chorizo-sausage.png'),
    pastrami: require('../assets/icons/items/pastrami-deli.png'),
    pickles: require('../assets/icons/items/pickles-in-a-jar.png'),
    pickle: require('../assets/icons/items/pickles-in-a-jar.png'),

    // ── Meat ────────────────────────────────────────────────────────────────
    chicken: require('../assets/icons/items/chicken-breast.png'),
    'chicken breast': require('../assets/icons/items/chicken-breast.png'),
    'chicken thighs': require('../assets/icons/items/chicken-thighs.png'),
    'whole chicken': require('../assets/icons/items/whole-chicken.png'),
    beef: require('../assets/icons/items/beef-steak.png'),
    steak: require('../assets/icons/items/beef-steak.png'),
    'beef steak': require('../assets/icons/items/beef-steak.png'),
    'ground beef': require('../assets/icons/items/ground-beef.png'),
    mince: require('../assets/icons/items/ground-beef.png'),
    'minced meat': require('../assets/icons/items/ground-beef.png'),
    'minced beef': require('../assets/icons/items/ground-beef.png'),
    bacon: require('../assets/icons/items/bacon-strips.png'),
    'bacon strips': require('../assets/icons/items/bacon-strips.png'),
    sausage: require('../assets/icons/items/sausages.png'),
    sausages: require('../assets/icons/items/sausages.png'),
    lamb: require('../assets/icons/items/lamb.png'),
    'lamb chops': require('../assets/icons/items/lamb.png'),
    turkey: require('../assets/icons/items/turkey.png'),
    duck: require('../assets/icons/items/duck.png'),
    pork: require('../assets/icons/items/pork-meat.png'),
    'pork chops': require('../assets/icons/items/pork-meat.png'),
    veal: require('../assets/icons/items/veal-meat.png'),
    liver: require('../assets/icons/items/liver.png'),
    'frozen chicken': require('../assets/icons/items/frozen-chicken.png'),

    // ── Fish & Seafood ───────────────────────────────────────────────────────
    fish: require('../assets/icons/items/fish.png'),
    salmon: require('../assets/icons/items/salmon-fish.png'),
    tuna: require('../assets/icons/items/tuna-fish.png'),
    cod: require('../assets/icons/items/cod-fish.png'),
    trout: require('../assets/icons/items/trout-fish.png'),
    'sea bass': require('../assets/icons/items/sea-bass-fish.png'),
    shrimp: require('../assets/icons/items/shrimp.png'),
    prawns: require('../assets/icons/items/shrimp.png'),
    prawn: require('../assets/icons/items/shrimp.png'),
    squid: require('../assets/icons/items/squid.png'),
    calamari: require('../assets/icons/items/squid.png'),
    crab: require('../assets/icons/items/crab.png'),
    lobster: require('../assets/icons/items/lobster.png'),
    anchovies: require('../assets/icons/items/anchovies-fish.png'),
    anchovy: require('../assets/icons/items/anchovies-fish.png'),
    'fish fingers': require('../assets/icons/items/fish-fingers.png'),
    'fish sticks': require('../assets/icons/items/fish-fingers.png'),
    'frozen fish': require('../assets/icons/items/frozen-fish.png'),

    // ── Dairy ────────────────────────────────────────────────────────────────
    milk: require('../assets/icons/items/milk.png'),
    'almond milk': require('../assets/icons/items/almond-milk-carton.png'),
    butter: require('../assets/icons/items/butter.png'),
    margarine: require('../assets/icons/items/margarine.png'),
    egg: require('../assets/icons/items/eggs.png'),
    eggs: require('../assets/icons/items/eggs.png'),
    cream: require('../assets/icons/items/cream.png'),
    'whipping cream': require('../assets/icons/items/whipping-cream.png'),
    'whipped cream': require('../assets/icons/items/whipped-cream-can.png'),
    mozzarella: require('../assets/icons/items/mozzarella.png'),
    parmesan: require('../assets/icons/items/parmigiano-grana.png'),
    parmigiano: require('../assets/icons/items/parmigiano-grana.png'),
    grana: require('../assets/icons/items/parmigiano-grana.png'),
    cheddar: require('../assets/icons/items/cheddar.png'),
    ricotta: require('../assets/icons/items/ricotta-cheese.png'),
    'cottage cheese': require('../assets/icons/items/cottage-cheese.png'),
    yogurt: require('../assets/icons/items/plain-yogurt.png'),
    yoghurt: require('../assets/icons/items/plain-yogurt.png'),
    'greek yogurt': require('../assets/icons/items/plain-yogurt.png'),
    'plain yogurt': require('../assets/icons/items/plain-yogurt.png'),

    // ── Canned Goods & Condiments ────────────────────────────────────────────
    'coconut milk': require('../assets/icons/items/coconut-milk.png'),
    'soy sauce': require('../assets/icons/items/soy-sauce-bottle.png'),
    honey: require('../assets/icons/items/honey-jar.png'),
    marmalade: require('../assets/icons/items/marmalade-jar.png'),

    // ── Pasta / Rice / Cereal ────────────────────────────────────────────────
    pasta: require('../assets/icons/items/pasta-penne-spaghetti.png'),
    penne: require('../assets/icons/items/pasta-penne-spaghetti.png'),
    spaghetti: require('../assets/icons/items/pasta-penne-spaghetti.png'),
    fusilli: require('../assets/icons/items/pasta-penne-spaghetti.png'),
    macaroni: require('../assets/icons/items/pasta-penne-spaghetti.png'),
    rice: require('../assets/icons/items/rice.png'),
    porridge: require('../assets/icons/items/porridge-in-a-bowl.png'),
    oats: require('../assets/icons/items/porridge-in-a-bowl.png'),
    oatmeal: require('../assets/icons/items/porridge-in-a-bowl.png'),
    cereal: require('../assets/icons/items/cereal-breakfast.png'),
    cornflakes: require('../assets/icons/items/cereal-breakfast.png'),
    muesli: require('../assets/icons/items/cereal-breakfast.png'),

    // ── Baking ───────────────────────────────────────────────────────────────
    flour: require('../assets/icons/items/flour-bag.png'),
    'flour bag': require('../assets/icons/items/flour-bag.png'),
    sugar: require('../assets/icons/items/sugar.png'),
    'baking soda': require('../assets/icons/items/baking-soda.png'),
    yeast: require('../assets/icons/items/yeast-packet.png'),
    vanilla: require('../assets/icons/items/vanilla-extract-bottle.png'),
    'vanilla extract': require('../assets/icons/items/vanilla-extract-bottle.png'),
    'chocolate chips': require('../assets/icons/items/chocolate-chips-bag.png'),
    cornstarch: require('../assets/icons/items/cornstarch.png'),
    cornflour: require('../assets/icons/items/cornstarch.png'),

    // ── Condiments & Spices ──────────────────────────────────────────────────
    salt: require('../assets/icons/items/salt-shaker.png'),
    'olive oil': require('../assets/icons/items/extra-virgin-olive-oil.png'),
    'extra virgin olive oil': require('../assets/icons/items/extra-virgin-olive-oil.png'),
    cinnamon: require('../assets/icons/items/cinnamon-sticks.png'),
    cumin: require('../assets/icons/items/cumin.png'),
    'curry powder': require('../assets/icons/items/curry-powder.png'),
    curry: require('../assets/icons/items/curry-powder.png'),

    // ── Snacks ───────────────────────────────────────────────────────────────
    crackers: require('../assets/icons/items/crackers.png'),
    cracker: require('../assets/icons/items/crackers.png'),
    crisps: require('../assets/icons/items/crisps-chips.png'),
    chips: require('../assets/icons/items/crisps-chips.png'),
    popcorn: require('../assets/icons/items/popcorn.png'),
    pretzels: require('../assets/icons/items/pretzels.png'),
    pretzel: require('../assets/icons/items/pretzels.png'),
    chocolate: require('../assets/icons/items/chocolate-bar.png'),
    'chocolate bar': require('../assets/icons/items/chocolate-bar.png'),
    'dark chocolate': require('../assets/icons/items/chocolate-bar.png'),
    'gummy bears': require('../assets/icons/items/gummy-bears.png'),
    gummies: require('../assets/icons/items/gummy-bears.png'),
    'granola bar': require('../assets/icons/items/granola-bar.png'),
    'granola bars': require('../assets/icons/items/granola-bar.png'),
    almonds: require('../assets/icons/items/almonds.png'),
    almond: require('../assets/icons/items/almonds.png'),
    cashews: require('../assets/icons/items/cashews.png'),
    cashew: require('../assets/icons/items/cashews.png'),
    peanuts: require('../assets/icons/items/peanuts.png'),
    peanut: require('../assets/icons/items/peanuts.png'),
    walnuts: require('../assets/icons/items/walnuts.png'),
    walnut: require('../assets/icons/items/walnuts.png'),
    pistachios: require('../assets/icons/items/pistachios.png'),
    pistachio: require('../assets/icons/items/pistachios.png'),
    nuts: require('../assets/icons/items/nuts.png'),
    'mixed nuts': require('../assets/icons/items/nuts.png'),
    'trail mix': require('../assets/icons/items/nuts.png'),
    raisins: require('../assets/icons/items/raisins.png'),
    raisin: require('../assets/icons/items/raisins.png'),
    'dried fruit': require('../assets/icons/items/raisins.png'),
    'rice cakes': require('../assets/icons/items/rice-cakes-moon-cakes.png'),
    'rice cake': require('../assets/icons/items/rice-cakes-moon-cakes.png'),

    // ── Beverages ────────────────────────────────────────────────────────────
    water: require('../assets/icons/items/mineral-water-bottle.png'),
    'mineral water': require('../assets/icons/items/mineral-water-bottle.png'),
    'sparkling water': require('../assets/icons/items/mineral-water-bottle.png'),
    tea: require('../assets/icons/items/tea.png'),
    'green tea': require('../assets/icons/items/green-tea.png'),
    beer: require('../assets/icons/items/beer-bottle.png'),
    wine: require('../assets/icons/items/red-wine-bottle.png'),
    'red wine': require('../assets/icons/items/red-wine-bottle.png'),
    cola: require('../assets/icons/items/cola-can.png'),
    soda: require('../assets/icons/items/soda-can.png'),
    'energy drink': require('../assets/icons/items/energy-drink.png'),
    smoothie: require('../assets/icons/items/smoothie-bottle.png'),

    // ── Frozen Foods ─────────────────────────────────────────────────────────
    pizza: require('../assets/icons/items/pizza.png'),

    // ── Personal Care ────────────────────────────────────────────────────────
    toothpaste: require('../assets/icons/items/toothpaste-tube.png'),
    toothbrush: require('../assets/icons/items/toothbrush.png'),
    deodorant: require('../assets/icons/items/deodorant-stick.png'),
    soap: require('../assets/icons/items/bar-of-soap.png'),
    'bar of soap': require('../assets/icons/items/bar-of-soap.png'),
    'hand soap': require('../assets/icons/items/hand-soap.png'),
    'shaving cream': require('../assets/icons/items/shaving-cream-can.png'),
    'lip balm': require('../assets/icons/items/lip-balm-stick.png'),
    tissues: require('../assets/icons/items/tissue-box.png'),
    tissue: require('../assets/icons/items/tissue-box.png'),

    // ── Household & Cleaning ─────────────────────────────────────────────────
    'dish soap': require('../assets/icons/items/dish-soap-bottle.png'),
    'dishwasher tablets': require('../assets/icons/items/dishwasher-tablets.png'),
    'dishwasher pods': require('../assets/icons/items/dishwasher-tablets.png'),
    bleach: require('../assets/icons/items/bleach.png'),
    cleaner: require('../assets/icons/items/cleaner-spray.png'),
    'all-purpose cleaner': require('../assets/icons/items/cleaner-spray.png'),
    'glass cleaner': require('../assets/icons/items/glass-cleaner-spray-bottle.png'),
    'fabric softener': require('../assets/icons/items/fabric-softener-bottle.png'),
    'trash bags': require('../assets/icons/items/trash-bags-roll.png'),
    'bin bags': require('../assets/icons/items/trash-bags-roll.png'),
    'garbage bags': require('../assets/icons/items/trash-bags-roll.png'),
    'aluminum foil': require('../assets/icons/items/aluminum-foil-roll.png'),
    'aluminium foil': require('../assets/icons/items/aluminum-foil-roll.png'),
    foil: require('../assets/icons/items/aluminum-foil-roll.png'),
    'plastic wrap': require('../assets/icons/items/plastic-wrap-roll.png'),
    'cling film': require('../assets/icons/items/plastic-wrap-roll.png'),
    'cling wrap': require('../assets/icons/items/plastic-wrap-roll.png'),
    batteries: require('../assets/icons/items/batteries.png'),
    battery: require('../assets/icons/items/batteries.png'),
    'light bulb': require('../assets/icons/items/light-bulb.png'),
    lightbulb: require('../assets/icons/items/light-bulb.png'),
    candle: require('../assets/icons/items/candle.png'),
    candles: require('../assets/icons/items/candle.png'),

    // ── Baby Items ───────────────────────────────────────────────────────────
    diapers: require('../assets/icons/items/diapers.png'),
    diaper: require('../assets/icons/items/diapers.png'),
    nappies: require('../assets/icons/items/diapers.png'),
    nappy: require('../assets/icons/items/diapers.png'),
    'baby wipes': require('../assets/icons/items/baby-wipes-wet-wipes-serviette.png'),
    'wet wipes': require('../assets/icons/items/baby-wipes-wet-wipes-serviette.png'),
    wipes: require('../assets/icons/items/baby-wipes-wet-wipes-serviette.png'),

    // ── Pet Care ─────────────────────────────────────────────────────────────
    'cat litter': require('../assets/icons/items/cat-litter.png'),
    'dog treats': require('../assets/icons/items/dog-treats.png'),
}

const LETTER_ICONS: Record<string, ImageSourcePropType> = {
    a: require('../assets/icons/letters/a.png'),
    b: require('../assets/icons/letters/b.png'),
    c: require('../assets/icons/letters/c.png'),
    d: require('../assets/icons/letters/d.png'),
    e: require('../assets/icons/letters/e.png'),
    f: require('../assets/icons/letters/f.png'),
    g: require('../assets/icons/letters/g.png'),
    h: require('../assets/icons/letters/h.png'),
    i: require('../assets/icons/letters/i.png'),
    j: require('../assets/icons/letters/j.png'),
    k: require('../assets/icons/letters/k.png'),
    l: require('../assets/icons/letters/l.png'),
    m: require('../assets/icons/letters/m.png'),
    n: require('../assets/icons/letters/n.png'),
    o: require('../assets/icons/letters/o.png'),
    p: require('../assets/icons/letters/p.png'),
    q: require('../assets/icons/letters/q.png'),
    r: require('../assets/icons/letters/r.png'),
    s: require('../assets/icons/letters/s.png'),
    t: require('../assets/icons/letters/t.png'),
    u: require('../assets/icons/letters/u.png'),
    v: require('../assets/icons/letters/v.png'),
    w: require('../assets/icons/letters/w.png'),
    x: require('../assets/icons/letters/x.png'),
    y: require('../assets/icons/letters/y.png'),
    z: require('../assets/icons/letters/z.png'),
}

// Manual translations for common grocery words missing from the auto-generated CSV map.
// Values must match existing ITEM_ICONS keys exactly (lowercase).
const MANUAL_TRANSLATIONS: Record<string, string> = {
    // ── Italian ──────────────────────────────────────────────────────────────
    // fruits
    'uva': 'grapes', 'uva bianca': 'grapes', 'uva nera': 'grapes',
    'fragole': 'strawberries', 'fragolina': 'strawberry',
    'mirtilli': 'blueberries',
    'more': 'blackberries',
    'ciliegie': 'cherries',
    'arance': 'oranges',
    'mango': 'mango',
    'ananas': 'pineapple',
    'anguria': 'watermelon', 'cocomero': 'watermelon',
    'melone': 'melon',
    'pesche': 'peaches',
    'pere': 'pears',
    'prugne': 'plums', 'prugna': 'plum',
    'nettarine': 'nectarines', 'nettarina': 'nectarine',
    'clementine': 'clementines', 'clementina': 'clementine',
    'mandarini': 'tangerines', 'mandarino': 'tangerine',
    'cocco': 'coconut', 'noce di cocco': 'coconut',
    'fichi': 'figs', 'fico': 'fig',
    'datteri': 'dates', 'dattero': 'date',
    'melograno': 'pomegranate',
    'pompelmo': 'grapefruit',
    'papaia': 'papaya', 'papaya': 'papaya',
    'frutto della passione': 'passion fruit',
    // vegetables
    'pomodori': 'tomatoes',
    'patate': 'potatoes', 'patata': 'potato',
    'patate dolci': 'sweet potatoes', 'patata dolce': 'sweet potato',
    'cipolle': 'onions',
    'cipollotti': 'spring onions', 'cipollotto': 'spring onion',
    'carote': 'carrots',
    'spinaci': 'spinach',
    'lattuga': 'lettuce', 'insalata': 'salad',
    'cetrioli': 'cucumbers', 'cetriolo': 'cucumber',
    'peperone': 'bell pepper', 'peperoni': 'bell peppers',
    'zucchina': 'zucchini', 'zucchine': 'zucchini',
    'melanzana': 'eggplant', 'melanzane': 'eggplant',
    'funghi': 'mushrooms', 'fungo': 'mushroom',
    'mais': 'corn',
    'fagiolini': 'green beans',
    'fagioli': 'beans', 'fagiolo': 'bean',
    'cavolo': 'cabbage',
    'cavolfiore': 'cauliflower',
    'asparagi': 'asparagus', 'asparago': 'asparagus',
    'porri': 'leeks', 'porro': 'leek',
    'ravanelli': 'radishes', 'ravanello': 'radish',
    'barbabietola': 'beetroot',
    'carciofi': 'artichokes', 'carciofo': 'artichoke',
    'pastinaca': 'parsnip',
    'rape': 'turnips', 'rapa': 'turnip',
    'zucca': 'butternut',
    'zenzero': 'ginger',
    'basilico': 'basil',
    'prezzemolo': 'parsley',
    'coriandolo': 'coriander',
    'aneto': 'dill',
    'rosmarino': 'rosemary',
    'origano': 'oregano',
    // meat
    'carne macinata': 'ground beef', 'macinato': 'ground beef',
    'bistecca': 'steak',
    'pancetta': 'bacon',
    'salsicce': 'sausages', 'salsiccia': 'sausage',
    'agnello': 'lamb',
    'tacchino': 'turkey',
    'anatra': 'duck',
    'maiale': 'pork',
    'vitello': 'veal',
    'fegato': 'liver',
    'pollo intero': 'whole chicken',
    'petto di pollo': 'chicken breast',
    'coscia di pollo': 'chicken thighs',
    // fish
    'pesce': 'fish',
    'salmone': 'salmon',
    'merluzzo': 'cod',
    'trota': 'trout',
    'branzino': 'sea bass', 'orata': 'sea bass',
    'gamberi': 'shrimp', 'gamberetto': 'shrimp',
    'calamari': 'squid', 'calamaro': 'squid',
    'granchio': 'crab',
    'astice': 'lobster', 'aragosta': 'lobster',
    'alici': 'anchovies', 'alice': 'anchovy', 'acciughe': 'anchovies', 'acciuga': 'anchovy',
    'bastoncini di pesce': 'fish fingers',
    // dairy & eggs
    'latte di mandorla': 'almond milk',
    'uova': 'eggs',
    'panna da montare': 'whipping cream',
    'panna montata': 'whipped cream',
    'fiocchi di latte': 'cottage cheese',
    'latte di cocco': 'coconut milk',
    'salsa di soia': 'soy sauce',
    'miele': 'honey',
    'marmellata': 'marmalade',
    // pantry
    'riso': 'rice',
    'avena': 'oats', "fiocchi d'avena": 'oats',
    'cereali': 'cereal',
    'bicarbonato': 'baking soda',
    'lievito': 'yeast',
    'vaniglia': 'vanilla',
    'amido di mais': 'cornstarch', 'maizena': 'cornstarch',
    "olio d'oliva": 'olive oil', 'olio extravergine': 'olive oil',
    'cannella': 'cinnamon',
    'cumino': 'cumin',
    // snacks & nuts
    'patatine': 'crisps',
    'salatini': 'pretzels',
    'cioccolato': 'chocolate',
    'tavoletta di cioccolato': 'chocolate bar',
    'orsetti di gomma': 'gummy bears',
    'barretta di cereali': 'granola bar',
    'mandorle': 'almonds', 'mandorla': 'almond',
    'anacardi': 'cashews', 'anacardio': 'cashew',
    'arachidi': 'peanuts', 'arachide': 'peanut',
    'noci': 'walnuts', 'noce': 'walnut',
    'pistacchi': 'pistachios', 'pistacchio': 'pistachio',
    'frutta secca': 'nuts',
    'uvetta': 'raisins',
    'gallette di riso': 'rice cakes',
    // beverages
    'acqua minerale': 'mineral water', 'acqua frizzante': 'sparkling water',
    'tè verde': 'green tea', 'te verde': 'green tea',
    'vino rosso': 'red wine',
    'bibita': 'soda',
    // bread & bakery
    'ciambella': 'donut',
    'torta': 'cake',
    'biscotto': 'biscuit', 'biscotti': 'biscuits',
    // personal care
    'dentifricio': 'toothpaste',
    'spazzolino': 'toothbrush',
    'deodorante': 'deodorant',
    'sapone': 'soap',
    'sapone per le mani': 'hand soap',
    'schiuma da barba': 'shaving cream',
    'balsamo labbra': 'lip balm',
    'fazzoletti': 'tissues',
    // household
    'detersivo per piatti': 'dish soap',
    'pastiglie lavastoviglie': 'dishwasher tablets',
    'candeggina': 'bleach',
    'detergente': 'cleaner',
    'ammorbidente': 'fabric softener',
    'sacchi della spazzatura': 'trash bags',
    'carta stagnola': 'aluminum foil',
    'pellicola trasparente': 'plastic wrap',
    'batterie': 'batteries', 'batteria': 'battery',
    'lampadina': 'light bulb',
    'candele': 'candles',
    // baby & pet
    'pannolini': 'diapers', 'pannolino': 'diaper',
    'salviettine umide': 'wet wipes',
    'lettiera per gatti': 'cat litter',

    // ── German ───────────────────────────────────────────────────────────────
    // fruits
    'apfel': 'apple', 'äpfel': 'apple',
    'birne': 'pear', 'birnen': 'pears',
    'erdbeere': 'strawberry', 'erdbeeren': 'strawberries',
    'heidelbeere': 'blueberry', 'heidelbeeren': 'blueberries',
    'brombeere': 'blackberry', 'brombeeren': 'blackberries',
    'kirsche': 'cherry', 'kirschen': 'cherries',
    'zitrone': 'lemon', 'zitronen': 'lemons',
    'orange': 'orange', 'orangen': 'oranges',
    'melone': 'melon',
    'wassermelone': 'watermelon',
    'pfirsich': 'peach', 'pfirsiche': 'peaches',
    'pflaume': 'plum', 'pflaumen': 'plums',
    'nektarine': 'nectarine', 'nektarinen': 'nectarines',
    'clementine': 'clementine', 'clementinen': 'clementines',
    'mandarine': 'tangerine', 'mandarinen': 'tangerines',
    'kokosnuss': 'coconut',
    'feige': 'fig', 'feigen': 'figs',
    'dattel': 'date', 'datteln': 'dates',
    'maracuja': 'passion fruit',
    'granatapfel': 'pomegranate',
    'weintraube': 'grape', 'weintrauben': 'grapes',
    'traube': 'grape', 'trauben': 'grapes',
    // vegetables
    'tomate': 'tomato', 'tomaten': 'tomatoes',
    'kartoffel': 'potato', 'kartoffeln': 'potatoes',
    'süßkartoffel': 'sweet potato', 'süßkartoffeln': 'sweet potatoes',
    'zwiebel': 'onion', 'zwiebeln': 'onions',
    'frühlingszwiebel': 'spring onion', 'frühlingszwiebeln': 'spring onions',
    'karotte': 'carrot', 'karotten': 'carrots',
    'möhre': 'carrot', 'möhren': 'carrots',
    'brokkoli': 'broccoli',
    'spinat': 'spinach',
    'salat': 'salad', 'kopfsalat': 'lettuce',
    'gurke': 'cucumber', 'gurken': 'cucumbers',
    'paprika': 'bell pepper',
    'pilz': 'mushroom', 'pilze': 'mushrooms',
    'champignon': 'mushroom', 'champignons': 'mushrooms',
    'grüne bohnen': 'green beans',
    'bohne': 'bean', 'bohnen': 'beans',
    'kohl': 'cabbage',
    'blumenkohl': 'cauliflower',
    'spargel': 'asparagus',
    'lauch': 'leek',
    'radieschen': 'radish',
    'rote bete': 'beetroot',
    'artischocke': 'artichoke', 'artischocken': 'artichokes',
    'pastinake': 'parsnip', 'pastinaken': 'parsnips',
    'rübe': 'turnip', 'rüben': 'turnips',
    'ingwer': 'ginger',
    'basilikum': 'basil',
    'petersilie': 'parsley',
    'koriander': 'coriander',
    'rosmarin': 'rosemary',
    // meat
    'hähnchen': 'chicken', 'hühnchen': 'chicken', 'huhn': 'chicken',
    'rindfleisch': 'beef',
    'hackfleisch': 'ground beef',
    'speck': 'bacon',
    'wurst': 'sausage', 'würstchen': 'sausages',
    'lamm': 'lamb',
    'truthahn': 'turkey', 'pute': 'turkey',
    'ente': 'duck',
    'schweinefleisch': 'pork',
    'kalbfleisch': 'veal',
    'leber': 'liver',
    // fish
    'fisch': 'fish',
    'lachs': 'salmon',
    'kabeljau': 'cod',
    'forelle': 'trout',
    'wolfsbarsch': 'sea bass',
    'garnele': 'shrimp', 'garnelen': 'shrimp',
    'tintenfisch': 'squid',
    'krabbe': 'crab', 'krabben': 'crab',
    'hummer': 'lobster',
    'sardelle': 'anchovy', 'sardellen': 'anchovies',
    'fischstäbchen': 'fish fingers',
    // dairy & eggs
    'mandelmilch': 'almond milk',
    'ei': 'egg', 'eier': 'eggs',
    'sahne': 'cream',
    'schlagsahne': 'whipping cream',
    'hüttenkäse': 'cottage cheese',
    'joghurt': 'yogurt',
    'kokosmilch': 'coconut milk',
    'sojasoße': 'soy sauce', 'sojasauce': 'soy sauce',
    'honig': 'honey',
    'marmelade': 'marmalade',
    // pantry
    'nudeln': 'pasta',
    'reis': 'rice',
    'haferflocken': 'oats',
    'cerealien': 'cereal',
    'natron': 'baking soda',
    'hefe': 'yeast',
    'vanille': 'vanilla',
    'maisstärke': 'cornstarch', 'speisestärke': 'cornstarch',
    'olivenöl': 'olive oil',
    'zimt': 'cinnamon',
    'kreuzkümmel': 'cumin',
    'currypulver': 'curry powder',
    // snacks & nuts
    'brezel': 'pretzel', 'brezeln': 'pretzels',
    'schokolade': 'chocolate',
    'gummibären': 'gummy bears',
    'müsliriegel': 'granola bar',
    'mandel': 'almond', 'mandeln': 'almonds',
    'erdnuss': 'peanut', 'erdnüsse': 'peanuts',
    'walnuss': 'walnut', 'walnüsse': 'walnuts',
    'pistazie': 'pistachio', 'pistazien': 'pistachios',
    'nüsse': 'nuts',
    'rosinen': 'raisins',
    'reiskuchen': 'rice cakes',
    // beverages
    'mineralwasser': 'mineral water',
    'grüner tee': 'green tea',
    'rotwein': 'red wine',
    'limonade': 'soda',
    // bread & bakery
    'brot': 'bread',
    'keks': 'biscuit', 'kekse': 'biscuits',
    'kuchen': 'cake',
    // personal care
    'zahnpasta': 'toothpaste',
    'zahnbürste': 'toothbrush',
    'seife': 'soap',
    'handseife': 'hand soap',
    'rasierschaum': 'shaving cream',
    'lippenpflege': 'lip balm',
    'taschentücher': 'tissues',
    // household
    'spülmittel': 'dish soap',
    'spülmaschinentabs': 'dishwasher tablets',
    'bleichmittel': 'bleach',
    'reiniger': 'cleaner',
    'glasreiniger': 'glass cleaner',
    'weichspüler': 'fabric softener',
    'müllbeutel': 'trash bags',
    'alufolie': 'aluminum foil',
    'frischhaltefolie': 'plastic wrap',
    'glühbirne': 'light bulb',
    'kerze': 'candle', 'kerzen': 'candles',
    // baby & pet
    'windel': 'diaper', 'windeln': 'diapers',
    'feuchttücher': 'wet wipes',
    'katzenstreu': 'cat litter',

    // ── French ───────────────────────────────────────────────────────────────
    // fruits
    'pomme': 'apple', 'pommes': 'apples',
    'banane': 'banana', 'bananes': 'bananas',
    'fraise': 'strawberry', 'fraises': 'strawberries',
    'myrtille': 'blueberry', 'myrtilles': 'blueberries',
    'mûre': 'blackberry', 'mûres': 'blackberries',
    'cerise': 'cherry', 'cerises': 'cherries',
    'citron': 'lemon', 'citrons': 'lemons',
    'pastèque': 'watermelon',
    'pêche': 'peach', 'pêches': 'peaches',
    'poire': 'pear', 'poires': 'pears',
    'prune': 'plum', 'prunes': 'plums',
    'nectarine': 'nectarine', 'nectarines': 'nectarines',
    'clémentine': 'clementine', 'clémentines': 'clementines',
    'mandarine': 'tangerine', 'mandarines': 'tangerines',
    'noix de coco': 'coconut',
    'figue': 'fig', 'figues': 'figs',
    'datte': 'date', 'dattes': 'dates',
    'fruit de la passion': 'passion fruit',
    'papaye': 'papaya',
    'grenade': 'pomegranate',
    'pamplemousse': 'grapefruit',
    'mangue': 'mango', 'mangues': 'mango',
    // vegetables
    'tomate': 'tomato', 'tomates': 'tomatoes',
    'pomme de terre': 'potato', 'pommes de terre': 'potatoes',
    'patate douce': 'sweet potato', 'patates douces': 'sweet potatoes',
    'oignon': 'onion', 'oignons': 'onions',
    'oignon nouveau': 'spring onion', 'oignons nouveaux': 'spring onions',
    'carotte': 'carrot', 'carottes': 'carrots',
    'brocoli': 'broccoli',
    'épinard': 'spinach', 'épinards': 'spinach',
    'salade': 'salad', 'laitue': 'lettuce',
    'concombre': 'cucumber', 'concombres': 'cucumbers',
    'poivron': 'bell pepper', 'poivrons': 'bell peppers',
    'champignon': 'mushroom', 'champignons': 'mushrooms',
    'maïs': 'corn',
    'haricots verts': 'green beans',
    'haricot': 'bean', 'haricots': 'beans',
    'chou': 'cabbage',
    'chou-fleur': 'cauliflower',
    'asperge': 'asparagus', 'asperges': 'asparagus',
    'poireau': 'leek', 'poireaux': 'leeks',
    'radis': 'radish',
    'betterave': 'beetroot',
    'artichaut': 'artichoke', 'artichauts': 'artichokes',
    'panais': 'parsnip',
    'navet': 'turnip', 'navets': 'turnips',
    'roquette': 'arugula',
    'gingembre': 'ginger',
    'basilic': 'basil',
    'persil': 'parsley',
    'coriandre': 'coriander',
    'aneth': 'dill',
    'romarin': 'rosemary',
    'origan': 'oregano',
    // meat
    'poulet': 'chicken',
    'blanc de poulet': 'chicken breast',
    'cuisses de poulet': 'chicken thighs',
    'bœuf': 'beef', 'boeuf': 'beef',
    'bœuf haché': 'ground beef', 'boeuf hache': 'ground beef',
    'lardons': 'bacon',
    'saucisse': 'sausage', 'saucisses': 'sausages',
    'agneau': 'lamb',
    'dinde': 'turkey',
    'canard': 'duck',
    'porc': 'pork',
    'veau': 'veal',
    'foie': 'liver',
    // fish
    'poisson': 'fish',
    'cabillaud': 'cod', 'morue': 'cod',
    'truite': 'trout',
    'bar': 'sea bass', 'loup de mer': 'sea bass',
    'crevette': 'shrimp', 'crevettes': 'shrimp',
    'calmar': 'squid', 'calmars': 'squid',
    'crabe': 'crab',
    'homard': 'lobster',
    'anchois': 'anchovies',
    'bâtonnets de poisson': 'fish fingers',
    // dairy & eggs
    'lait d\'amande': 'almond milk',
    'oeuf': 'egg', 'oeufs': 'eggs', 'œuf': 'egg', 'œufs': 'eggs',
    'crème': 'cream', 'crème fraîche': 'cream',
    'crème fouettée': 'whipped cream',
    'fromage blanc': 'cottage cheese',
    'yaourt': 'yogurt', 'yogourt': 'yogurt',
    'lait de coco': 'coconut milk',
    'sauce soja': 'soy sauce',
    'miel': 'honey',
    'confiture': 'marmalade',
    // pantry
    'pâtes': 'pasta',
    'riz': 'rice',
    "flocons d'avoine": 'oats',
    'céréales': 'cereal',
    'bicarbonate': 'baking soda',
    'levure': 'yeast',
    'vanille': 'vanilla',
    'fécule': 'cornstarch', 'maïzena': 'cornstarch',
    "huile d'olive": 'olive oil',
    'cannelle': 'cinnamon',
    // snacks & nuts
    'bretzel': 'pretzel', 'bretzels': 'pretzels',
    'chocolat': 'chocolate',
    'oursons en gomme': 'gummy bears',
    'amande': 'almond', 'amandes': 'almonds',
    'noix de cajou': 'cashew',
    'cacahuète': 'peanut', 'cacahuètes': 'peanuts',
    'noix': 'walnuts',
    'pistache': 'pistachio', 'pistaches': 'pistachios',
    'raisins secs': 'raisins',
    'galettes de riz': 'rice cakes',
    // beverages
    'eau': 'water', 'eau minérale': 'mineral water',
    'thé': 'tea', 'thé vert': 'green tea', 'the vert': 'green tea',
    'bière': 'beer',
    'vin': 'wine', 'vin rouge': 'red wine',
    'boisson énergisante': 'energy drink',
    // bread & bakery
    'pain': 'bread',
    'beignet': 'donut',
    'gâteau': 'cake',
    // personal care
    'dentifrice': 'toothpaste',
    'brosse à dents': 'toothbrush',
    'déodorant': 'deodorant',
    'savon': 'soap', 'savon liquide': 'hand soap',
    'crème à raser': 'shaving cream',
    'baume à lèvres': 'lip balm',
    'mouchoirs': 'tissues',
    // household
    'liquide vaisselle': 'dish soap',
    'pastilles lave-vaisselle': 'dishwasher tablets',
    "eau de javel": 'bleach',
    'nettoyant': 'cleaner',
    'nettoyant vitres': 'glass cleaner',
    'assouplissant': 'fabric softener',
    'sacs poubelle': 'trash bags',
    'papier aluminium': 'aluminum foil',
    'film alimentaire': 'plastic wrap',
    'pile': 'battery', 'piles': 'batteries',
    'ampoule': 'light bulb',
    'bougie': 'candle', 'bougies': 'candles',
    // baby & pet
    'couche': 'diaper', 'couches': 'diapers',
    'lingettes': 'wet wipes',
    "litière pour chat": 'cat litter',

    // ── Spanish ──────────────────────────────────────────────────────────────
    // fruits
    'manzana': 'apple', 'manzanas': 'apples',
    'plátano': 'banana', 'plátanos': 'bananas', 'banano': 'banana',
    'uva': 'grapes',
    'fresa': 'strawberry', 'fresas': 'strawberries',
    'arándano': 'blueberry', 'arándanos': 'blueberries',
    'mora': 'blackberry', 'moras': 'blackberries',
    'cereza': 'cherry', 'cerezas': 'cherries',
    'aguacate': 'avocado',
    'limón': 'lemon', 'limones': 'lemons', 'limon': 'lemon',
    'naranja': 'orange', 'naranjas': 'oranges',
    'pomelo': 'grapefruit',
    'melón': 'melon', 'melon': 'melon',
    'sandía': 'watermelon', 'sandia': 'watermelon',
    'piña': 'pineapple', 'pina': 'pineapple',
    'melocotón': 'peach', 'melocotones': 'peaches', 'durazno': 'peach',
    'pera': 'pear', 'peras': 'pears',
    'ciruela': 'plum', 'ciruelas': 'plums',
    'nectarina': 'nectarine', 'nectarinas': 'nectarines',
    'clementina': 'clementine', 'clementinas': 'clementines',
    'mandarina': 'tangerine', 'mandarinas': 'tangerines',
    'coco': 'coconut',
    'higo': 'fig', 'higos': 'figs',
    'dátil': 'date', 'dátiles': 'dates', 'datil': 'date',
    'maracuyá': 'passion fruit', 'maracuya': 'passion fruit',
    'granada': 'pomegranate',
    // vegetables
    'tomate': 'tomato', 'tomates': 'tomatoes',
    'patata': 'potato', 'patatas': 'potatoes', 'papa': 'potato', 'papas': 'potatoes',
    'boniato': 'sweet potato',
    'cebolla': 'onion', 'cebollas': 'onions',
    'cebolleta': 'spring onion', 'cebolletas': 'spring onions',
    'zanahoria': 'carrot', 'zanahorias': 'carrots',
    'brócoli': 'broccoli', 'brocoli': 'broccoli',
    'espinaca': 'spinach', 'espinacas': 'spinach',
    'ensalada': 'salad', 'lechuga': 'lettuce',
    'pepino': 'cucumber', 'pepinos': 'cucumbers',
    'pimiento': 'bell pepper', 'pimientos': 'bell peppers',
    'calabacín': 'zucchini', 'calabacin': 'zucchini',
    'berenjena': 'eggplant', 'berenjenas': 'eggplant',
    'champiñón': 'mushroom', 'champiñones': 'mushrooms', 'champinon': 'mushroom',
    'maíz': 'corn', 'maiz': 'corn',
    'judías verdes': 'green beans',
    'judía': 'bean', 'judías': 'beans',
    'col': 'cabbage', 'repollo': 'cabbage',
    'coliflor': 'cauliflower',
    'espárrago': 'asparagus', 'espárragos': 'asparagus', 'esparrago': 'asparagus',
    'puerro': 'leek', 'puerros': 'leeks',
    'rábano': 'radish', 'rábanos': 'radishes', 'rabano': 'radish',
    'remolacha': 'beetroot',
    'alcachofa': 'artichoke', 'alcachofas': 'artichokes',
    'chirivía': 'parsnip',
    'nabo': 'turnip', 'nabos': 'turnips',
    'rúcula': 'arugula', 'rucula': 'arugula',
    'jengibre': 'ginger',
    'albahaca': 'basil',
    'perejil': 'parsley',
    'eneldo': 'dill',
    'romero': 'rosemary',
    'orégano': 'oregano', 'oregano': 'oregano',
    // meat
    'pechuga de pollo': 'chicken breast',
    'muslos de pollo': 'chicken thighs',
    'pollo entero': 'whole chicken',
    'carne de res': 'beef', 'ternera': 'beef',
    'carne picada': 'ground beef',
    'tocino': 'bacon', 'beicon': 'bacon',
    'salchicha': 'sausage', 'salchichas': 'sausages',
    'cordero': 'lamb',
    'pavo': 'turkey',
    'pato': 'duck',
    'cerdo': 'pork',
    'hígado': 'liver', 'higado': 'liver',
    // fish
    'pescado': 'fish',
    'salmón': 'salmon', 'salmon': 'salmon',
    'atún': 'tuna', 'atun': 'tuna',
    'bacalao': 'cod',
    'trucha': 'trout',
    'lubina': 'sea bass',
    'gamba': 'shrimp', 'gambas': 'shrimp', 'camarón': 'shrimp', 'camaron': 'shrimp',
    'calamar': 'squid', 'calamares': 'squid',
    'cangrejo': 'crab',
    'langosta': 'lobster',
    'anchoa': 'anchovy', 'anchoas': 'anchovies',
    // dairy & eggs
    'leche de almendras': 'almond milk',
    'huevo': 'egg', 'huevos': 'eggs',
    'nata': 'cream',
    'nata para montar': 'whipping cream',
    'requesón': 'cottage cheese',
    'yogur': 'yogurt',
    'leche de coco': 'coconut milk',
    'salsa de soja': 'soy sauce',
    'mermelada': 'marmalade',
    // pantry
    'arroz': 'rice',
    'avena': 'oats', 'copos de avena': 'oats',
    'cereales': 'cereal',
    'bicarbonato': 'baking soda',
    'levadura': 'yeast',
    'vainilla': 'vanilla',
    'maicena': 'cornstarch',
    'aceite de oliva': 'olive oil',
    'canela': 'cinnamon',
    'comino': 'cumin',
    // snacks & nuts
    'patatas fritas': 'crisps',
    'palomitas': 'popcorn',
    'ositos de goma': 'gummy bears',
    'almendra': 'almond', 'almendras': 'almonds',
    'anacardo': 'cashew', 'anacardos': 'cashews',
    'cacahuete': 'peanut', 'cacahuetes': 'peanuts',
    'nuez': 'walnut', 'nueces': 'walnuts',
    'pistacho': 'pistachio', 'pistachos': 'pistachios',
    'pasas': 'raisins',
    // beverages
    'agua mineral': 'mineral water',
    'té verde': 'green tea', 'te verde': 'green tea',
    'cerveza': 'beer',
    'vino tinto': 'red wine',
    'refresco': 'soda',
    'bebida energética': 'energy drink',
    // bread & bakery
    'pan': 'bread',
    'galleta': 'biscuit', 'galletas': 'biscuits',
    // personal care
    'dentífrico': 'toothpaste', 'dentifrico': 'toothpaste',
    'cepillo de dientes': 'toothbrush',
    'desodorante': 'deodorant',
    'jabón': 'soap', 'jabon': 'soap',
    'jabón de manos': 'hand soap',
    'crema de afeitar': 'shaving cream',
    'bálsamo labial': 'lip balm',
    'pañuelos': 'tissues',
    // household
    'lavavajillas': 'dish soap',
    'pastillas lavavajillas': 'dishwasher tablets',
    'lejía': 'bleach', 'lejia': 'bleach',
    'limpiador': 'cleaner',
    'limpiacristales': 'glass cleaner',
    'suavizante': 'fabric softener',
    'bolsas de basura': 'trash bags',
    'papel de aluminio': 'aluminum foil',
    'film transparente': 'plastic wrap',
    'pila': 'battery', 'pilas': 'batteries',
    'bombilla': 'light bulb',
    'vela': 'candle', 'velas': 'candles',
    // baby & pet
    'pañal': 'diaper', 'pañales': 'diapers',
    'toallitas húmedas': 'wet wipes',
    'arena para gatos': 'cat litter',

    // ── Portuguese ───────────────────────────────────────────────────────────
    'maçã': 'apple', 'maçãs': 'apples', 'maca': 'apple',
    'banana': 'banana', 'bananas': 'bananas',
    'morango': 'strawberry', 'morangos': 'strawberries',
    'mirtilo': 'blueberry', 'mirtilos': 'blueberries',
    'cereja': 'cherry', 'cerejas': 'cherries',
    'limão': 'lemon', 'limoes': 'lemons',
    'laranja': 'orange', 'laranjas': 'oranges',
    'melancia': 'watermelon',
    'pêssego': 'peach', 'pessego': 'peach',
    'pera': 'pear', 'peras': 'pears',
    'ameixa': 'plum', 'ameixas': 'plums',
    'uva': 'grapes',
    'abacate': 'avocado',
    'coco': 'coconut',
    'figo': 'fig', 'figos': 'figs',
    'romã': 'pomegranate',
    'tomate': 'tomato', 'tomates': 'tomatoes',
    'batata': 'potato', 'batatas': 'potatoes',
    'batata doce': 'sweet potato',
    'cebola': 'onion', 'cebolas': 'onions',
    'cebolinha': 'spring onion',
    'cenoura': 'carrot', 'cenouras': 'carrots',
    'espinafre': 'spinach',
    'pepino': 'cucumber',
    'pimento': 'bell pepper', 'pimentos': 'bell peppers',
    'abobrinha': 'zucchini',
    'berinjela': 'eggplant',
    'cogumelo': 'mushroom', 'cogumelos': 'mushrooms',
    'milho': 'corn',
    'feijão verde': 'green beans', 'feijao verde': 'green beans',
    'feijão': 'beans', 'feijao': 'beans',
    'repolho': 'cabbage',
    'couve-flor': 'cauliflower',
    'espargo': 'asparagus', 'espargos': 'asparagus',
    'alho-francês': 'leek',
    'rabanete': 'radish',
    'beterraba': 'beetroot',
    'alcachofra': 'artichoke',
    'nabo': 'turnip',
    'gengibre': 'ginger',
    'manjericão': 'basil',
    'salsa': 'parsley',
    'coentro': 'coriander',
    'alecrim': 'rosemary',
    'orégano': 'oregano',
    'frango': 'chicken',
    'carne moída': 'ground beef',
    'linguiça': 'sausage',
    'cordeiro': 'lamb',
    'peru': 'turkey',
    'pato': 'duck',
    'porco': 'pork',
    'vitela': 'veal',
    'fígado': 'liver', 'figado': 'liver',
    'peixe': 'fish',
    'camarão': 'shrimp', 'camarao': 'shrimp',
    'lula': 'squid',
    'caranguejo': 'crab',
    'lagosta': 'lobster',
    'anchova': 'anchovy',
    'leite de amêndoa': 'almond milk',
    'ovo': 'egg', 'ovos': 'eggs',
    'creme de leite': 'cream',
    'queijo cottage': 'cottage cheese',
    'iogurte': 'yogurt',
    'leite de coco': 'coconut milk',
    'molho de soja': 'soy sauce',
    'mel': 'honey',
    'geléia': 'marmalade', 'geleia': 'marmalade',
    'arroz': 'rice',
    'aveia': 'oats',
    'farinha': 'flour',
    'açúcar': 'sugar', 'acucar': 'sugar',
    'fermento': 'yeast',
    'baunilha': 'vanilla',
    'amido de milho': 'cornstarch',
    'azeite': 'olive oil',
    'canela': 'cinnamon',
    'cominho': 'cumin',
    'pão': 'bread', 'pao': 'bread',
    'amêndoa': 'almond', 'amendoa': 'almond', 'amêndoas': 'almonds',
    'castanha de caju': 'cashew',
    'amendoim': 'peanut', 'amendoins': 'peanuts',
    'noz': 'walnut', 'nozes': 'walnuts',
    'pistache': 'pistachio',
    'uva-passa': 'raisins',
    'água': 'water', 'agua': 'water',
    'água mineral': 'mineral water',
    'chá': 'tea', 'cha': 'tea',
    'chá verde': 'green tea',
    'cerveja': 'beer',
    'vinho': 'wine', 'vinho tinto': 'red wine',
    'refrigerante': 'soda',

    // ── Dutch ─────────────────────────────────────────────────────────────────
    'appel': 'apple', 'appels': 'apples',
    'banaan': 'banana', 'bananen': 'bananas',
    'aardbei': 'strawberry', 'aardbeien': 'strawberries',
    'bosbes': 'blueberry', 'bosbessen': 'blueberries',
    'braam': 'blackberry', 'bramen': 'blackberries',
    'kers': 'cherry', 'kersen': 'cherries',
    'citroen': 'lemon', 'citroenen': 'lemons',
    'sinaasappel': 'orange', 'sinaasappels': 'oranges',
    'watermeloen': 'watermelon',
    'druif': 'grape', 'druiven': 'grapes',
    'perzik': 'peach', 'perziken': 'peaches',
    'peer': 'pear', 'peren': 'pears',
    'pruim': 'plum', 'pruimen': 'plums',
    'nectarine': 'nectarine',
    'kokosnoot': 'coconut',
    'vijg': 'fig', 'vijgen': 'figs',
    'tomaat': 'tomato', 'tomaten': 'tomatoes',
    'aardappel': 'potato', 'aardappelen': 'potatoes',
    'zoete aardappel': 'sweet potato',
    'ui': 'onion', 'uien': 'onions',
    'wortel': 'carrot', 'wortels': 'carrots',
    'broccoli': 'broccoli',
    'spinazie': 'spinach',
    'sla': 'salad',
    'komkommer': 'cucumber', 'komkommers': 'cucumbers',
    'paprika': 'bell pepper',
    'courgette': 'zucchini',
    'aubergine': 'eggplant',
    'paddenstoel': 'mushroom', 'paddenstoelen': 'mushrooms',
    'maïs': 'corn', 'mais': 'corn',
    'sperziebonen': 'green beans',
    'boon': 'bean', 'bonen': 'beans',
    'kool': 'cabbage',
    'bloemkool': 'cauliflower',
    'asperge': 'asparagus', 'asperges': 'asparagus',
    'prei': 'leek',
    'radijs': 'radish',
    'rode biet': 'beetroot',
    'artisjok': 'artichoke',
    'pastinaak': 'parsnip',
    'raap': 'turnip', 'rapen': 'turnips',
    'rucola': 'arugula',
    'gember': 'ginger',
    'basilicum': 'basil',
    'peterselie': 'parsley',
    'koriander': 'coriander',
    'rozemarijn': 'rosemary',
    'oregano': 'oregano',
    'kip': 'chicken',
    'kipfilet': 'chicken breast',
    'rundvlees': 'beef',
    'gehakt': 'ground beef',
    'spek': 'bacon',
    'worst': 'sausage', 'worsten': 'sausages',
    'lam': 'lamb',
    'kalkoen': 'turkey',
    'eend': 'duck',
    'varkensvlees': 'pork',
    'kalfsvlees': 'veal',
    'vis': 'fish',
    'zalm': 'salmon',
    'tonijn': 'tuna',
    'kabeljauw': 'cod',
    'forel': 'trout',
    'zeebaars': 'sea bass',
    'garnaal': 'shrimp', 'garnalen': 'shrimp',
    'inktvis': 'squid',
    'krab': 'crab',
    'kreeft': 'lobster',
    'ansjovis': 'anchovies',
    'melk': 'milk',
    'amandelmelk': 'almond milk',
    'ei': 'egg', 'eieren': 'eggs',
    'room': 'cream',
    'slagroom': 'whipping cream',
    'hüttenkäse': 'cottage cheese',
    'yoghurt': 'yogurt',
    'kokosmelk': 'coconut milk',
    'sojasaus': 'soy sauce',
    'honing': 'honey',
    'jam': 'marmalade',
    'rijst': 'rice',
    'havermout': 'oats',
    'meel': 'flour',
    'suiker': 'sugar',
    'gist': 'yeast',
    'vanille': 'vanilla',
    'maïszetmeel': 'cornstarch',
    'olijfolie': 'olive oil',
    'kaneel': 'cinnamon',
    'komijn': 'cumin',
    'brood': 'bread',
    'amandel': 'almond', 'amandelen': 'almonds',
    'cashew': 'cashew',
    'pinda': 'peanut', "pinda's": 'peanuts',
    'walnoot': 'walnut', 'walnoten': 'walnuts',
    'pistache': 'pistachio',
    'rozijnen': 'raisins',
    'water': 'water',
    'mineraalwater': 'mineral water',
    'groene thee': 'green tea',
    'bier': 'beer',
    'wijn': 'wine', 'rode wijn': 'red wine',
    'frisdrank': 'soda',
}

// Pre-compute multi-word keys sorted by length (longest first) for priority matching
const MULTI_WORD_KEYS = Object.keys(ITEM_ICONS)
    .filter((k) => k.includes(' '))
    .sort((a, b) => b.length - a.length)

const SINGLE_WORD_KEYS = Object.keys(ITEM_ICONS).filter((k) => !k.includes(' '))

const NORMALIZED_TRANSLATED_ITEM_TO_EN: Record<string, string> = {}
for (const [source, target] of Object.entries(TRANSLATED_ITEM_TO_EN)) {
    const normalizedSource = normalizeForLookup(source)
    if (normalizedSource && !NORMALIZED_TRANSLATED_ITEM_TO_EN[normalizedSource]) {
        NORMALIZED_TRANSLATED_ITEM_TO_EN[normalizedSource] = target
    }
}

const NORMALIZED_MANUAL_TRANSLATIONS: Record<string, string> = {}
for (const [source, target] of Object.entries(MANUAL_TRANSLATIONS)) {
    const normalizedSource = normalizeForLookup(source)
    if (normalizedSource && !NORMALIZED_MANUAL_TRANSLATIONS[normalizedSource]) {
        NORMALIZED_MANUAL_TRANSLATIONS[normalizedSource] = target
    }
}

function normalizeForLookup(text: string): string {
    return text
        .toLowerCase()
        .normalize('NFD')
        .replace(/[\u0300-\u036f]/g, '')
        .replace(/[’']/g, '')
        .replace(/[-_/]/g, ' ')
        .replace(/[^a-z0-9\s]/g, ' ')
        .replace(/\s+/g, ' ')
        .trim()
}

function stripQuantifiers(text: string): string {
    return text
        .replace(/\b\d+(\.\d+)?\s*(%|g|kg|ml|l|lb|oz|ct|pk|pack)\b/gi, '')
        .replace(
            /\b(organic|fresh|free-range|whole|large|small|medium|extra|lite|light|low-fat|fat-free|sugar-free|gluten-free|natural|raw|smoked|sliced|diced|chopped|ground|minced|boneless|skinless)\b/gi,
            '',
        )
        .replace(/\s+/g, ' ')
        .trim()
}

type IconResult = { type: 'image' | 'letter'; source: ImageSourcePropType }

function translateToEnglish(text: string): string | undefined {
    const normalized = normalizeForLookup(text)
    return (
        MANUAL_TRANSLATIONS[text] ??
        TRANSLATED_ITEM_TO_EN[text] ??
        NORMALIZED_MANUAL_TRANSLATIONS[normalized] ??
        NORMALIZED_TRANSLATED_ITEM_TO_EN[normalized]
    )
}

export function getIconForItem(text: string): IconResult {
    const normalized = normalizeForLookup(text)
    const stripped = stripQuantifiers(normalized)

    // 1. Exact match on normalized text
    if (ITEM_ICONS[normalized]) {
        return { type: 'image', source: ITEM_ICONS[normalized] }
    }

    // 2. Exact match on stripped text
    if (stripped && stripped !== normalized && ITEM_ICONS[stripped]) {
        return { type: 'image', source: ITEM_ICONS[stripped] }
    }

    // 3. Translate to English and retry (covers all non-English item names)
    const enEquiv = translateToEnglish(normalized) ?? translateToEnglish(stripped)
    if (enEquiv) {
        if (ITEM_ICONS[enEquiv]) {
            return { type: 'image', source: ITEM_ICONS[enEquiv] }
        }
        // Also try stripped version of the English equivalent
        const enStripped = stripQuantifiers(enEquiv)
        if (enStripped !== enEquiv && ITEM_ICONS[enStripped]) {
            return { type: 'image', source: ITEM_ICONS[enStripped] }
        }
    }

    // 4. Multi-word key match (longest first — "bell peppers" before "pepper")
    for (const key of MULTI_WORD_KEYS) {
        if (normalized.includes(key) || stripped.includes(key)) {
            return { type: 'image', source: ITEM_ICONS[key] }
        }
    }

    // 5. Word match — split text into words, check each against single-word keys
    const words = normalized.split(/\s+/)
    for (const word of words) {
        if (ITEM_ICONS[word]) {
            return { type: 'image', source: ITEM_ICONS[word] }
        }
        // Also try translating individual words
        const wordEn = translateToEnglish(word)
        if (wordEn && ITEM_ICONS[wordEn]) {
            return { type: 'image', source: ITEM_ICONS[wordEn] }
        }
    }

    // 6. Substring match — check if any single-word key is contained in the text
    for (const key of SINGLE_WORD_KEYS) {
        if (normalized.includes(key) || stripped.includes(key)) {
            return { type: 'image', source: ITEM_ICONS[key] }
        }
    }

    // 7. Letter fallback
    const letterMatch = text.match(/[a-zA-Z]/)
    const letter = letterMatch ? letterMatch[0].toLowerCase() : 'a'
    return { type: 'letter', source: LETTER_ICONS[letter] }
}
